language: php

php:
  - 5.5
  - 5.6
  - 7

install:
  - composer install --no-interaction

before_script:
  - sudo pip install codecov

script:
  - php vendor/bin/phpunit --coverage-clover=coverage.xml

after_success:
  - codecov

notifications:
  email:
    - gulturyan@gmail.com